import { BusFront, Route as RouteIcon, Users, Bell, Check, ArrowRight, Navigation } from 'lucide-react';
import type { State } from '../lib/transport';
export type AdminArea = 'overview' | 'routes' | 'bus' | 'people' | 'alerts' | 'evening';
export const adminAreas: {id:AdminArea;label:string}[] = [{id:'overview',label:'Overview'},{id:'routes',label:'Route & stops'},{id:'bus',label:'Company bus'},{id:'people',label:'Workers & drivers'},{id:'evening',label:'Evening & weekly shifts'},{id:'alerts',label:'Email alerts'}];
export default function AdminOverview({state,onOpen,onDrive}:{state:State;onOpen:(area:AdminArea)=>void;onDrive:()=>void}) {
 const bus=state.buses[0],route=state.routes.find(r=>r.id===bus?.routeId),drivers=state.members.filter(m=>m.role==='driver'),workers=state.members.filter(m=>m.role==='worker');
 const steps=[{area:'routes' as const,title:'Save the pickup route',detail:state.routes.length?`${state.routes.length} saved route${state.routes.length===1?'':'s'} · review pickup stops and times`:'Record the route with your phone, or enter pickup stops manually.',done:state.routes.length>0}, {area:'bus' as const,title:'Set up your one company bus',detail:bus&&route?`${bus.name} · ${route.name}`:'Add its name, registration and a saved route to enable driver trips.',done:!!bus&&!!route},{area:'people' as const,title:'Approve workers and drivers',detail:`${drivers.length} driver${drivers.length===1?'':'s'} · ${workers.length} worker${workers.length===1?'':'s'} approved`,done:drivers.length>0&&workers.length>0},{area:'alerts' as const,title:'Check arrival email delivery',detail:state.emailReady?'Sender connected. Send yourself a test email.':'Connect the email sender before using arrival emails.',done:state.emailReady}];
 return <div className="admin-overview"><div className="admin-stats">{[{icon:BusFront,label:'Company bus',value:bus?.name??'Not set up',area:'bus' as const},{icon:RouteIcon,label:'Assigned pickup stops',value:route?String(route.stops.length):'No route',area:'routes' as const},{icon:Users,label:'Approved people',value:String(state.members.length),area:'people' as const},{icon:Bell,label:'Arrival email sender',value:state.emailReady?'Connected':'Needs setup',area:'alerts' as const}].map(({icon:Icon,...s})=><button className="panel admin-stat" key={s.area} onClick={()=>onOpen(s.area)}><span className="summary-icon purple"><Icon size={21}/></span><span><small>{s.label}</small><strong>{s.value}</strong></span><ArrowRight size={16}/></button>)}</div><div className="admin-overview-grid"><section className="panel admin-checklist"><div className="section-heading"><div><p className="eyebrow">SETUP CHECKLIST</p><h2>Get ready for the morning</h2></div><span className="status-tag">{steps.filter(s=>s.done).length}/4 ready</span></div>{steps.map((step,i)=><button className="admin-checklist-item" key={step.area} onClick={()=>onOpen(step.area)}><span className={`admin-check-number ${step.done?'complete':''}`}>{step.done?<Check size={16}/>:i+1}</span><span><strong>{step.title}</strong><small>{step.detail}</small></span><ArrowRight size={18}/></button>)}</section><section className="panel admin-duty"><p className="eyebrow">DAILY OPERATION</p><h2>One bus. A shared duty.</h2><p>Morning pickup runs <strong>06:00–08:00 GMT</strong> with driver swaps. Evening home drop-offs run <strong>18:00–21:00 GMT</strong> with one assigned night driver.</p><div className="assigned-bus"><BusFront size={22}/><div><strong>{bus?.name??'Add the company bus first'}</strong><small>{bus?.plate??'Registration pending'} · {route?.name??'Route pending'}</small></div></div><button className="button full" onClick={bus&&route?onDrive:()=>onOpen('bus')}><Navigation size={18}/>{bus&&route?'Open driver controls':'Set up the company bus'}</button><p className="help-text">Set up evening duty in Evening & weekly shifts. Use Test mode in Driver to check tracking outside service hours without sending worker alerts.</p></section></div></div>;
}
