'use client';
import { useEffect,useRef,useState } from 'react';
import type { Map as LeafletMap,LayerGroup } from 'leaflet';
import { renderToStaticMarkup } from 'react-dom/server';
import { BusFront, LocateFixed, Maximize } from 'lucide-react';
import type {Route,Bus,Trip,PickupPoint} from '@/lib/transport';
import { freshness,routePath } from '@/lib/transport';
export default function FleetMap({routes,buses,trips,selected,onSelect,demo,pickup}:{routes:Route[];buses:Bus[];trips:Trip[];selected:string;onSelect:(id:string)=>void;demo:boolean;pickup?:PickupPoint|null}){
 const element=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layer=useRef<LayerGroup|null>(null),library=useRef<typeof import('leaflet')|null>(null);const [ready,setReady]=useState(false),[tileError,setTileError]=useState(false);const selectedRef=useRef(onSelect);selectedRef.current=onSelect;
 useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled||!element.current)return;library.current=L;map.current=L.map(element.current,{zoomControl:false}).setView([4.924,-1.764],13);L.control.zoom({position:'bottomleft'}).addTo(map.current);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> contributors',maxZoom:19});tiles.on('tileerror',()=>setTileError(true));tiles.addTo(map.current);layer.current=L.layerGroup().addTo(map.current);setReady(true);});return()=>{cancelled=true;map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready||!library.current||!map.current||!layer.current)return;const L=library.current;layer.current.clearLayers();routes.forEach(r=>{const pts=routePath(r).map(s=>[s.lat,s.lng] as [number,number]);L.polyline(pts,{color:r.color,weight:5,opacity:.65,dashArray:'7 7'}).addTo(layer.current!);r.stops.forEach((s,i)=>{const el=document.createElement('div');el.textContent=`${i+1}. ${s.name} · ${s.time}`;L.circleMarker([s.lat,s.lng],{radius:6,color:r.color,weight:3,fillColor:'#fff',fillOpacity:1}).bindTooltip(el.outerHTML).addTo(layer.current!);});});buses.forEach(b=>{const t=trips.find(x=>x.busId===b.id);if(!t||t.lat===null||t.lng===null)return;const r=routes.find(x=>x.id===(t.routeId??b.routeId));const stale=!demo&&['Location outdated','Weak GPS','Driver handover','Waiting for GPS'].includes(freshness(t));const el=document.createElement('div');el.className='map-popup';const strong=document.createElement('strong');strong.textContent=b.name;const small=document.createElement('p');small.textContent=`${demo?'Sample journey':freshness(t)} · ${t.driverName}`;el.appendChild(strong);el.appendChild(small);const marker=L.marker([t.lat,t.lng],{icon:L.divIcon({className:'bus-marker-wrap',html:`<div class="bus-marker ${b.id===selected?'selected':''} ${stale?'stale':''}" style="--route-color:${r?.color??'#7C3AED'}">${renderToStaticMarkup(<BusFront size={20}/>)}<span>${b.name.replace(/[^a-zA-Z0-9 ]/g,'').slice(0,20)}</span></div>`,iconSize:[78,42],iconAnchor:[39,21]})}).bindPopup(el.outerHTML).on('click',()=>selectedRef.current(b.id));marker.addTo(layer.current!);});if(pickup){const label=document.createElement('div');label.textContent=`Your destination: ${pickup.name}`;L.circleMarker([pickup.lat,pickup.lng],{radius:9,color:'#0F172A',weight:4,fillColor:'#fff',fillOpacity:1}).bindTooltip(label.outerHTML).addTo(layer.current);}},[ready,routes,buses,trips,selected,demo,pickup]);
 useEffect(()=>{if(!ready||!map.current||!routes.length)return;const p=routes.flatMap(r=>routePath(r).map(s=>[s.lat,s.lng] as [number,number]));if(p.length)map.current.fitBounds(p,{padding:[65,65]});},[ready,JSON.stringify(routes)]);
 useEffect(()=>{if(!element.current||!map.current)return;const observer=new ResizeObserver(()=>map.current?.invalidateSize());observer.observe(element.current);return()=>observer.disconnect();},[ready]);
 function focus(){const t=trips.find(t=>t.busId===selected);if(t?.lat!=null&&t.lng!=null)map.current?.setView([t.lat,t.lng],15);}
 return <div className="map-shell"><div ref={element} className="map" aria-label="Map of the company bus location and ordered pickup stops"/><div className="map-top"><span className="map-label">{demo?'SAMPLE BUS MAP':'BUS MAP'}</span><div className="map-tools"><button aria-label="Center on company bus" title="Center on company bus" onClick={focus}><LocateFixed size={19}/></button><button aria-label="Fit bus route" title="Fit bus route" onClick={()=>{const p=routes.flatMap(r=>routePath(r).map(s=>[s.lat,s.lng] as [number,number]));if(p.length)map.current?.fitBounds(p,{padding:[65,65]});}}><Maximize size={19}/></button></div></div><div className="map-legend">{routes.map(r=><span key={r.id}><i style={{background:r.color}}/>{r.name}</span>)}<small>{routes.some(r=>r.recorded)?'Recorded GPS trail':'Lines connect stops; they are not driving directions.'}</small></div>{tileError&&<div className="tile-error">Map tiles could not load. Bus coordinates and pickup details are still available.</div>}</div>;
}
