'use client';
import { useEffect,useRef,useState } from 'react';
import type {Map as LeafletMap,LayerGroup} from 'leaflet';
import type {Point} from '@/lib/transport';
import {Maximize} from 'lucide-react';
export default function PointMap({path,point,onPick,follow=false}:{path:Point[];point?:Point|null;onPick?:(p:Point)=>void;follow?:boolean}){
 const element=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layer=useRef<LayerGroup|null>(null),library=useRef<typeof import('leaflet')|null>(null),pick=useRef(onPick),fitted=useRef(false),currentPath=useRef(path);pick.current=onPick;currentPath.current=path;
 const [ready,setReady]=useState(false),[tileError,setTileError]=useState(false);
 useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled||!element.current)return;library.current=L;map.current=L.map(element.current,{scrollWheelZoom:false}).setView([4.924,-1.764],13);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>',maxZoom:19});tiles.on('tileerror',()=>setTileError(true));tiles.addTo(map.current);layer.current=L.layerGroup().addTo(map.current);map.current.on('click',e=>pick.current?.({lat:e.latlng.lat,lng:e.latlng.lng}));setReady(true);});return()=>{cancelled=true;map.current?.remove();};},[]);
 useEffect(()=>{if(!ready||!library.current||!layer.current||!map.current)return;const L=library.current;layer.current.clearLayers();if(path.length){L.polyline(path.map(p=>[p.lat,p.lng]),{color:'#7C3AED',weight:5,opacity:.85}).addTo(layer.current);L.circleMarker([path[0].lat,path[0].lng],{radius:5,color:'#0F172A',fillOpacity:1}).bindTooltip('Route start').addTo(layer.current);if(!fitted.current&&path.length>=2&&element.current?.clientWidth){map.current.fitBounds(path.map(p=>[p.lat,p.lng]),{padding:[35,35],maxZoom:16});fitted.current=true;}if(follow&&element.current?.clientWidth)map.current.panTo([path.at(-1)!.lat,path.at(-1)!.lng]);}if(point)L.circleMarker([point.lat,point.lng],{radius:10,color:'#0F172A',weight:4,fillColor:'#fff',fillOpacity:1}).bindTooltip(onPick?'Your pickup point':'Latest recorded fix').addTo(layer.current);},[ready,JSON.stringify(path),point?.lat,point?.lng,follow,!!onPick]);
 useEffect(()=>{if(!map.current||!element.current)return;const observer=new ResizeObserver(()=>{map.current?.invalidateSize();const p=currentPath.current;if(!fitted.current&&element.current?.clientWidth&&p.length>=2){map.current?.fitBounds(p.map(p=>[p.lat,p.lng]),{padding:[35,35],maxZoom:16});fitted.current=true;}});observer.observe(element.current);return()=>observer.disconnect();},[ready]);
 return <div className="point-map-shell"><div ref={element} className="point-map" aria-label={onPick?'Tap the bus route to select your pickup point':'GPS recorded route map'}/><button className="point-map-fit" type="button" aria-label="Show entire route" onClick={()=>{if(path.length)map.current?.fitBounds(path.map(p=>[p.lat,p.lng]),{padding:[35,35],maxZoom:16});}}><Maximize size={18}/></button>{tileError&&<p className="point-map-warning" role="status">Map tiles are unavailable. Your saved route and coordinates are retained.</p>}</div>;
}
