'use client';
import {request} from '@/lib/client';
import {useEffect,useRef,useState} from 'react';
import {Navigation,Square,Play,MapPin,Save,Trash2} from 'lucide-react';
import {toast} from 'sonner';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import PointMap from './point-map';
import {distance,pathLength,type RouteRecording,type RecordedPoint} from '@/lib/transport';

export default function RouteRecorder({initial,onSaved}:{initial:RouteRecording|null;onSaved:()=>Promise<void>}){
 const [record,setRecord]=useState(initial),[points,setPoints]=useState<RecordedPoint[]>(initial?.points??[]),[name,setName]=useState(initial?.name??'Morning pickup route'),[active,setActive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[queued,setQueued]=useState(0);
 const session=useRef(initial),trail=useRef<RecordedPoint[]>(initial?.points??[]),pending=useRef<RecordedPoint[]>([]),count=useRef(initial?.pointCount??0),watch=useRef<number|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),wake=useRef<any>(null),flushing=useRef(false),activeRef=useRef(false),mounted=useRef(true);
 useEffect(()=>{if(!activeRef.current&&!pending.current.length){session.current=initial;trail.current=initial?.points??[];count.current=initial?.pointCount??0;setRecord(initial);setPoints(trail.current);if(initial)setName(initial.name);}},[initial?.id,initial?.pointCount,initial?.status]);
 function halt(){activeRef.current=false;if(watch.current!==null)navigator.geolocation.clearWatch(watch.current);watch.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;wake.current?.release().catch(()=>{});wake.current=null;if(mounted.current)setActive(false);}
 async function flush(){if(flushing.current||!session.current||!pending.current.length)return;flushing.current=true;try{while(pending.current.length){const batch=pending.current.slice(0,100),expected=count.current;const response=await request({action:'recording-append',recordingId:session.current.id,expectedCount:expected,points:batch});pending.current.splice(0,batch.length);count.current=expected+batch.length;if(mounted.current){setQueued(pending.current.length);setMessage(`${count.current} GPS points saved. ${pending.current.length?`${pending.current.length} waiting to save.`:''}`);}if(response.pointCount!==count.current){halt();throw new Error('Another screen added points. Reload before recording further.');}}}catch(e){if((e as any).status===409||(e as any).status===400)halt();if(mounted.current)setMessage((e as any).status?(e as Error).message:'Connection lost. Recorded fixes are waiting to save; keep this page open.');throw e;}finally{flushing.current=false;}}
 function addFix(fix:GeolocationPosition){if(!activeRef.current)return;const p={lat:fix.coords.latitude,lng:fix.coords.longitude,accuracy:fix.coords.accuracy,capturedAt:Math.round(fix.timestamp)};if(p.accuracy>50){setMessage(`Waiting for stronger GPS · accuracy ±${Math.round(p.accuracy)} m`);return;}const last=trail.current.at(-1);if(last&&(p.capturedAt<=last.capturedAt||distance(p,last)<15))return;if(trail.current.length>=10000){halt();setMessage('Recording is full. Finish and review this route.');return;}trail.current=[...trail.current,p];pending.current.push(p);setPoints(trail.current);setQueued(pending.current.length);if(pending.current.length>=25)void flush().catch(()=>{});}
 async function acquireWake(){try{if('wakeLock'in navigator)wake.current=await(navigator as any).wakeLock.request('screen');}catch{}}
 useEffect(()=>{mounted.current=true;const warn=(e:BeforeUnloadEvent)=>{if(activeRef.current||pending.current.length){e.preventDefault();e.returnValue='';}};const visible=()=>{if(document.visibilityState==='visible'&&activeRef.current)void acquireWake();};window.addEventListener('beforeunload',warn);document.addEventListener('visibilitychange',visible);return()=>{mounted.current=false;halt();void flush().catch(()=>{});window.removeEventListener('beforeunload',warn);document.removeEventListener('visibilitychange',visible);};},[]);
 async function begin(){if(!navigator.geolocation){toast.error('Phone location is unavailable in this browser.');return;}setBusy(true);try{const fix=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}));if(pending.current.length)await flush();const latest=(await request()).recording as RouteRecording|null;let r:RouteRecording;if(latest){r=latest;await request({action:'recording-resume',recordingId:r.id});}else{r=(await request({action:'recording-start',name})).recording;}session.current={...r,status:'recording'};trail.current=[...r.points];count.current=r.pointCount;setRecord(session.current);setPoints(trail.current);setName(r.name);activeRef.current=true;setActive(true);setMessage('Recording your phone GPS. Keep this page open while travelling the bus route.');await acquireWake();addFix(fix);watch.current=navigator.geolocation.watchPosition(addFix,e=>setMessage(e.code===1?'Location permission denied. Enable it in phone settings.':'GPS signal interrupted. Keep the screen open and wait for a fresh fix.'),{enableHighAccuracy:true,timeout:20000,maximumAge:0});timer.current=setInterval(()=>void flush().catch(()=>{}),10000);await onSaved();}catch(e){toast.error((e as Error).message||'Allow phone location access to start recording.');}finally{setBusy(false);}}
 async function finish(){halt();setBusy(true);try{if(flushing.current){setMessage('Points are still saving. Tap Finish & review again in a moment.');return;}await flush();if(!session.current)return;await request({action:'recording-review',recordingId:session.current.id});session.current={...session.current,status:'review',pointCount:count.current,points:trail.current};setRecord(session.current);setMessage('Review the trail before saving. Record in the same direction the bus will travel.');await onSaved();}catch(e){toast.error((e as Error).message||'Keep this page open and retry saving.');}finally{setBusy(false);}}
 async function save(){if(!session.current)return;setBusy(true);try{await request({action:'recording-save',recordingId:session.current.id,name});setRecord(null);session.current=null;trail.current=[];setPoints([]);toast.success('Recorded route saved. Assign it to the company bus below.');await onSaved();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function discard(){halt();if(!session.current)return;setBusy(true);try{await request({action:'recording-discard',recordingId:session.current.id});pending.current=[];trail.current=[];session.current=null;setQueued(0);setRecord(null);setPoints([]);setMessage('');await onSaved();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel route-recorder"><div className="section-heading"><div><p className="eyebrow">ADMINISTRATOR</p><h2>Record the bus route</h2></div><span className={`status-tag ${active?'live':''}`}>{active?'Recording GPS':record?'Saved draft':'Ready to record'}</span></div><p>Travel the pickup route with this page open on your phone. Your GPS trail becomes the bus route after you review and save it.</p><label>Route name<input value={name} maxLength={100} onChange={e=>setName(e.target.value)} disabled={active} placeholder="Morning pickup route"/></label><PointMap path={points} point={points.at(-1)} follow={active}/><div className="recording-stats"><span><MapPin size={17}/>{points.length} GPS points</span><span>{(pathLength(points)/1000).toFixed(2)} km recorded</span><span>{queued?`${queued} points waiting to save`:'All received points saved'}</span></div><p className="help-text" role="status">{message||'Location is requested only after you tap Record route. Drafts already saved can be resumed on this phone.'}</p><div className="recorder-actions">{active?<button className="button" disabled={busy} onClick={()=>void finish()}><Square size={17}/>Stop & review</button>:<button className="button" disabled={busy||!name.trim()} onClick={()=>void begin()}>{record?<Play size={17}/>:<Navigation size={17}/>} {busy?'Waiting for phone location…':record?'Resume recording':'Record route'}</button>}{record&&!active&&record.status==='recording'&&<button className="button secondary" disabled={busy} onClick={()=>void finish()}>Finish & review</button>}{record?.status==='review'&&!active&&<button className="button secondary" disabled={busy||!!queued||!name.trim()} onClick={()=>void save()}><Save size={17}/>Save recorded route</button>}{record&&<AlertDialog><AlertDialogTrigger asChild><button className="button secondary" disabled={busy}><Trash2 size={17}/>Discard draft</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard this recording?</AlertDialogTitle><AlertDialogDescription>The recorded trail and any unsaved fixes will be removed. Existing bus routes will stay available.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep draft</AlertDialogCancel><AlertDialogAction onClick={()=>void discard()}>Discard recording</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div><p className="help-text">Use a passenger’s phone, or set up recording while parked. Keep the phone charging and the screen unlocked; phone browsers can pause GPS in the background. Only you as administrator can record and save routes.</p></section>;
}
