import assert from 'node:assert/strict';
import {testRuntime} from './test-runtime.mjs';
const mf=await testRuntime();
try{
const db=await mf.getD1Database('DB');
let checks=0;
async function call(who=null,body=null,expected=200,origin=null,raw=false){if(body&&typeof body==='object'&&['location','end','next-stop','delay','offer-handover','cancel-handover','accept-handover'].includes(body.action))body={driverEpoch:0,...body};const headers={};if(who){headers['oai-authenticated-user-id']=who;headers['oai-authenticated-user-email']=`${who}@example.test`;}if(body!==null)headers['content-type']='application/json';if(origin)headers.origin=origin;const res=await mf.dispatchFetch('https://pilot.test/api/transport',{method:body!==null?'POST':'GET',headers,body:body!==null?(raw?body:JSON.stringify(body)):undefined});const data=await res.json();assert.ok((Array.isArray(expected)?expected:[expected]).includes(res.status),JSON.stringify({who,body,status:res.status,data,expected}));checks++;return data;}
await call(null,null,401);await call('admin');await call('admin',{action:'setup',company:'Test company'});await call('stranger',null,403);await call('admin',{action:'setup',company:'Other'},409);
for(const [user,role] of [['worker','worker'],['driver-a','driver'],['driver-b','driver']])await call('admin',{action:'member',member:{email:`${user}@example.test`,name:user,role}});
const route={id:'route-test',name:'Test route',color:'#2168e8',stops:[{id:'a',name:'Pickup A',lat:4.9,lng:-1.7,time:'06:10'},{id:'b',name:'Pickup B',lat:4.91,lng:-1.71,time:'06:30'}]};
await call('worker',{action:'route',route},403);await call('admin',{action:'route',route});await call('admin',{action:'bus',bus:{id:'bus-test',name:'Test bus',plate:'TEST',routeId:route.id}});
await call('admin',{action:'bus',bus:{id:'second-bus',name:'Other bus',plate:'OTHER',routeId:route.id}},409);
await call('admin',{action:'bus',bus:{name:'Other bus',plate:'OTHER',routeId:route.id}},409);
await assert.rejects(db.prepare('INSERT INTO buses (id,name,plate,route_id) VALUES (?,?,?,?)').bind('race-bus','Race','RACE',route.id).run());checks++;
await call('admin',{action:'bus',bus:{id:'bus-test',name:'Shared company bus',plate:'TEST',routeId:route.id}});
assert.equal((await call('admin')).buses.length,1);
const state=await call('worker');const shift={date:state.today,busId:'bus-test',routeId:route.id,stopId:'a',onShift:true,radius:1000};await call('worker',{action:'shift',shift});assert.equal((await call('worker')).shift.onShift,1);await call('worker',{action:'shift',shift:{...shift,stopId:'wrong'}},400);await call('worker',{action:'shift',shift:{...shift,onShift:false}});assert.equal((await call('worker')).shift.onShift,0);
await call('worker',{action:'start',busId:'bus-test',test:true},403);const tid=(await call('driver-a',{action:'start',busId:'bus-test',test:true})).tripId;await call('driver-b',{action:'start',busId:'bus-test',test:true},409);await call('driver-b',{action:'end',tripId:tid},409);
const fix={action:'location',tripId:tid,lat:4.9,lng:-1.7,accuracy:10,speed:0,capturedAt:Date.now()};await call('worker',fix,403);await call('driver-a',{...fix,capturedAt:0},400);await call('driver-a',fix);assert.equal((await call('worker')).alerts.length,0);assert.equal((await call('admin')).trips[0].lat,4.9);await call('admin',{action:'route',route},409);await call('driver-a',{action:'next-stop',tripId:tid,nextStop:2},400);await call('driver-a',{action:'next-stop',tripId:tid,nextStop:1});
const beforeSwap=(await call('driver-a')).trips[0];
await call('driver-a',{action:'delay',tripId:tid,minutes:5});
await call('worker',{action:'offer-handover',tripId:tid,email:'driver-b@example.test'},403);
await call('worker',{...fix,action:'accept-handover'},403);
await call('driver-a',{action:'offer-handover',tripId:tid,email:'worker@example.test'},400);
await call('driver-a',{action:'offer-handover',tripId:tid,email:'stranger@example.test'},400);
await call('driver-a',{action:'offer-handover',tripId:tid,email:'driver-a@example.test'},400);
assert.equal((await call('driver-a')).members.length,3,'drivers see only approved driver/admin handover choices');
assert.equal((await call('worker')).members.length,0,'workers do not see driver email directory');
await call('driver-a',{action:'offer-handover',tripId:tid,email:'driver-b@example.test'});
const pending=(await call('driver-b')).trips[0];assert.equal(pending.handoverEmail,'driver-b@example.test');assert.equal(pending.driverId,'driver-a');assert.equal(pending.driverEpoch,1);
assert.equal((await call('worker')).trips[0].handoverEmail,null,'workers cannot read the nominated driver email');
await call('driver-a',{...fix,capturedAt:Date.now()},409);
await call('driver-a',{...fix,driverEpoch:1,capturedAt:Date.now()},409);
await call('driver-a',{action:'next-stop',tripId:tid,driverEpoch:1,nextStop:2},409);
await call('driver-a',{action:'delay',tripId:tid,driverEpoch:1,minutes:10},409);
await call('admin',{...fix,action:'accept-handover',driverEpoch:1,capturedAt:Date.now()},403);
await call('driver-b',{...fix,action:'accept-handover',driverEpoch:0,capturedAt:Date.now()},409);
await call('driver-b',{...fix,action:'accept-handover',driverEpoch:1,capturedAt:0},400);
assert.equal((await call('driver-b')).trips[0].driverId,'driver-a','failed GPS validation leaves ownership unchanged');
await call('driver-a',{action:'cancel-handover',tripId:tid,driverEpoch:1});
await call('driver-b',{...fix,action:'accept-handover',driverEpoch:1,capturedAt:Date.now()},403);
await call('driver-a',{...fix,capturedAt:Date.now()},409);
await call('driver-a',{...fix,driverEpoch:2,capturedAt:Date.now()});
await call('driver-a',{action:'offer-handover',tripId:tid,driverEpoch:2,email:'driver-b@example.test'});
const accepted=await Promise.allSettled([call('driver-b',{...fix,action:'accept-handover',driverEpoch:3,capturedAt:Date.now()},[200,403,409]),call('driver-b',{...fix,action:'accept-handover',driverEpoch:3,capturedAt:Date.now()},[200,403,409])]);
for(const result of accepted)assert.equal(result.status,'fulfilled',String(result.reason));
assert.equal(accepted.filter(r=>r.value?.ok).length,1,'only one simultaneous acceptance wins');
const continued=(await call('driver-b')).trips[0];assert.equal(continued.id,tid);assert.equal(continued.driverId,'driver-b');assert.equal(continued.driverEpoch,4);assert.equal(continued.handoverEmail,null);assert.equal(continued.nextStop,1);assert.equal(continued.delayMinutes,5);assert.equal(continued.startedAt,beforeSwap.startedAt);assert.equal(continued.routeId,beforeSwap.routeId);assert.equal(continued.busId,beforeSwap.busId);
for(const action of [{...fix,capturedAt:Date.now()},{action:'next-stop',tripId:tid,nextStop:2},{action:'delay',tripId:tid,minutes:30},{action:'end',tripId:tid}])await call('driver-a',{...action,driverEpoch:2},409);
await call('driver-b',{action:'offer-handover',tripId:tid,driverEpoch:4,email:'driver-a@example.test'});
await call('driver-a',{...fix,action:'accept-handover',driverEpoch:5,capturedAt:Date.now()});
await call('driver-a',{...fix,capturedAt:Date.now()},409);
await call('driver-a',{...fix,driverEpoch:6,capturedAt:Date.now()});
await call('driver-a',{action:'offer-handover',tripId:tid,driverEpoch:6,email:'driver-b@example.test'});
const raced=await Promise.allSettled([call('driver-a',{action:'cancel-handover',tripId:tid,driverEpoch:7},[200,409]),call('driver-b',{...fix,action:'accept-handover',driverEpoch:7,capturedAt:Date.now()},[200,403,409])]);
for(const result of raced)assert.equal(result.status,'fulfilled',String(result.reason));
assert.equal(raced.filter(r=>r.value?.ok).length,1,'cancel/accept race has one winner');
const finalDuty=(await call('admin')).trips[0];assert.equal(finalDuty.driverEpoch,8);assert.equal(finalDuty.handoverEmail,null);assert.equal(finalDuty.nextStop,1);
await call(finalDuty.driverId,{action:'end',tripId:tid,driverEpoch:8});const tid2=(await call('driver-b',{action:'start',busId:'bus-test',test:true})).tripId;assert.equal((await call('admin')).trips[0].driverId,'driver-b');await call('driver-b',{action:'end',tripId:tid2});
await call('worker',{action:'recording-start',name:'Forbidden'},403);await call('driver-a',{action:'recording-start',name:'Forbidden'},403);
const recording=(await call('admin',{action:'recording-start',name:'Recorded morning route'})).recording;
await call('admin',{action:'recording-start',name:'Duplicate'},409);
assert.equal((await call('worker')).recording,null,'recording drafts are private to the administrator');
const points=[0,1,2].map(i=>({lat:4.9+i*.001,lng:-1.7,accuracy:10,capturedAt:recording.createdAt+i*5000}));
await call('worker',{action:'recording-append',recordingId:recording.id,expectedCount:0,points},403);
await call('admin',{action:'recording-append',recordingId:recording.id,expectedCount:0,points:[{...points[0],accuracy:200}]},400);
await call('admin',{action:'recording-append',recordingId:recording.id,expectedCount:0,points});
assert.equal((await call('admin',{action:'recording-append',recordingId:recording.id,expectedCount:0,points})).pointCount,3,'lost-response replay does not duplicate the trail');
await call('admin',{action:'recording-append',recordingId:recording.id,expectedCount:0,points:[{...points[0],lat:4.91}]},409);
await call('admin',{action:'recording-save',recordingId:recording.id,name:'Too early'},409);
await call('admin',{action:'recording-review',recordingId:recording.id});
await call('admin',{action:'recording-append',recordingId:recording.id,expectedCount:3,points:[{...points[2],capturedAt:points[2].capturedAt+1000}]},409);
await call('admin',{action:'recording-resume',recordingId:recording.id});await call('admin',{action:'recording-review',recordingId:recording.id});
const saved=(await call('admin',{action:'recording-save',recordingId:recording.id,name:'Recorded morning route'})).routeId;
assert.equal((await call('admin')).recording,null);const recorded=(await call('worker')).routes.find(r=>r.id===saved);assert.equal(recorded.path.length,3);assert.equal(recorded.recorded,1);
await call('admin',{action:'bus',bus:{id:'bus-test',name:'Shared company bus',plate:'TEST',routeId:saved}});
await call('worker',{action:'pickup',pickup:{lat:40,lng:40,name:'Wrong place',radius:3000,emailArrival:true}},400);
await call('worker',{action:'pickup',pickup:{lat:4.9015,lng:-1.7,name:'My junction',radius:3000,emailArrival:true}});
const profile=(await call('worker')).pickup;await call('worker',{action:'pickup',pickup:{lat:profile.lat,lng:profile.lng,name:'My junction',radius:3000,emailArrival:true}});assert.ok(Math.abs((await call('worker')).pickup.offset-profile.offset)<.01,'saving a pin again does not move it along the trail');assert.ok(profile.offset>100);assert.equal(profile.radius,3000);assert.equal((await call('driver-a')).pickup,null,'pickup pins are private to their worker');
const selectedShift={...shift,routeId:saved,usePickup:true,radius:3000,emailArrival:true};await call('worker',{action:'shift',shift:selectedShift});assert.equal((await call('worker')).shift.pickup.name,'My junction');
await call('worker',{action:'test-email'},403);assert.equal((await call('admin',{action:'test-email'})).status,'not-configured');
await call('admin',{action:'route',route:{id:saved,name:'Revised route',color:'#BE5CA9',stops:recorded.stops}});
await call('worker',{action:'shift',shift:selectedShift},400);assert.equal((await call('worker')).pickup.routeRevision,1);assert.equal((await call('worker')).routes.find(r=>r.id===saved).revision,2);
const discarded=(await call('admin',{action:'recording-start',name:'Discard me'})).recording;await call('admin',{action:'recording-discard',recordingId:discarded.id});assert.equal((await call('admin')).recording,null);
await call('worker',{action:'shift',shift:{...shift,date:'2026-13-03'}},400);await call('worker','{broken',400,null,true);await call('admin',{action:'company',company:'Forged'},403,'https://other.test');

console.log(`${checks} Transport checks passed: auth, allowlist, roles, saved shifts, GPS freshness, simulation isolation, single-bus enforcement, bus ownership, same-trip handovers, cancellation and acceptance races, stale phone isolation after repeated swaps, stop order, GPS route recording, replay-safe draft saving, private map pickup profiles, route revisions, input validation.`);
}finally{await mf.dispose();}
